name = "sherlly-pages-proxy"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."

[[services]]
binding = "WORKER"
service = "sherlly-server"
environment = "production"

[env.production]
name = "sherlly-pages-proxy"
